pipeline {
  agent any
  stages {

    stage('Install Dependencies') {
      steps {
         dir("devops_day1") {

    bat 'npm install'

}
     
      }

    }
    stage('Run Tests') {
 steps {
         dir("devops_day1") {

    bat 'npm test'

}
     
      }

    }
  }
}